<?php

declare(strict_types=1);

namespace Vi\Validation\Compilation;

use Vi\Validation\Execution\CompiledField;
use Vi\Validation\Execution\CompiledSchema;
use Vi\Validation\Rules\NativeCompilableInterface;
use Vi\Validation\Rules\RuleInterface;
use ReflectionClass;

/**
 * NativeCompiler generates highly optimized PHP code for validation schemas.
 * It inlines rules that declare themselves native-compilable to minimize
 * method calls and object allocations.
 *
 * Compatibility contract: a native validator must never change validation
 * semantics compared to ValidatorEngine. If a schema contains any rule that
 * cannot be inlined, compile() throws UnsupportedNativeRuleException instead
 * of silently omitting the rule. Callers must catch it (or check
 * canCompile() up front) and fall back to ValidatorEngine for that schema.
 *
 * Whether a rule is inlinable is never guessed from its class name: it is
 * exactly the set of rules implementing Rules\NativeCompilableInterface (see
 * isSupported()). That interface also carries the actual codegen
 * (RuleInterface::compileNative()), so this class only owns the mechanics
 * that are the same for every field - the emptiness guard, sometimes/
 * nullable/bail wrapping, and value extraction - never rule-specific logic.
 */
final class NativeCompiler
{
    public const COMPILER_VERSION = '2.0.0';

    /**
     * Check whether every rule in the schema can be natively inlined.
     *
     * Use this to decide, ahead of time, whether it is safe to call
     * compile() for a given schema.
     */
    public function canCompile(CompiledSchema $schema): bool
    {
        return $this->findUnsupportedRules($schema) === [];
    }

    /**
     * List the rules in the schema that cannot be natively inlined, as
     * "field:RuleClass" strings. An empty list means the schema is fully
     * native-compilable.
     *
     * @return list<string>
     */
    public function findUnsupportedRules(CompiledSchema $schema): array
    {
        $unsupported = [];

        foreach ($schema->getFields() as $field) {
            // exclude*/exclusion marker rules are consumed into CompiledField's exclusion
            // flags and never appear in getRules(), so compileField() has no way to see
            // them; inlining this field would silently ignore the exclusion. Refuse instead.
            if ($field->hasExclusionSemantics()) {
                $unsupported[] = $field->getName() . ':exclusion-semantics';
            }

            foreach ($field->getRules() as $rule) {
                if (!$this->isSupported($rule)) {
                    $unsupported[] = $field->getName() . ':' . get_class($rule);
                }
            }
        }

        return $unsupported;
    }

    /**
     * Whether a single rule instance can be natively inlined.
     *
     * True iff the rule implements NativeCompilableInterface - there is no
     * other path to "supported" (no class-name list, no capability
     * guessing), so a new rule is unsupported by default until it opts in.
     */
    public function isSupported(RuleInterface $rule): bool
    {
        return $rule instanceof NativeCompilableInterface;
    }

    /**
     * Compile a schema into optimized PHP code.
     *
     * @throws UnsupportedNativeRuleException if the schema contains a rule
     *         that cannot be natively inlined. Callers must fall back to
     *         ValidatorEngine in that case rather than using a partial
     *         native validator.
     */
    public function compile(CompiledSchema $schema): string
    {
        $unsupported = $this->findUnsupportedRules($schema);
        if ($unsupported !== []) {
            throw new UnsupportedNativeRuleException(
                'Cannot natively compile schema: unsupported rule(s) found: '
                . implode(', ', $unsupported)
                . '. This schema must be validated with ValidatorEngine instead.'
            );
        }

        $code = "<?php\n\n";
        $code .= "declare(strict_types=1);\n\n";
        $code .= "/**\n";
        $code .= " * Optimized validation function generated by NativeCompiler.\n";
        $code .= " * Compiler Version: " . self::COMPILER_VERSION . "\n";
        $code .= " * PHP Version: " . PHP_VERSION . " (" . PHP_VERSION_ID . ")\n";
        $code .= " * Generated at: " . date('Y-m-d H:i:s') . "\n";
        $code .= " */\n";
        $code .= "return function(array \$data) {\n";
        $code .= "    \$errors = [];\n";
        $code .= "    \$hasErrors = false;\n";
        $code .= "    \$excludedFields = [];\n\n";

        foreach ($schema->getFields() as $field) {
            $code .= $this->compileField($field);
        }

        $code .= "    return [\n";
        $code .= "        'valid' => !\$hasErrors,\n";
        $code .= "        'errors' => \$errors,\n";
        $code .= "        'excluded_fields' => \$excludedFields,\n";
        $code .= "    ];\n";
        $code .= "};\n";

        return $code;
    }

    /**
     * Generate a unique key for the rules that includes PHP version and compiler version.
     *
     * The raw rules array (as passed to SchemaBuilder::setRulesArray()) may contain
     * Closures (inline rule callbacks) or arbitrary RuleInterface objects, and PHP's
     * serialize() throws on a Closure rather than silently ignoring it. Since a schema
     * containing any such rule is never natively compilable anyway (see isSupported()),
     * the exact key doesn't need to be content-stable for them - it only needs to never
     * crash the caller (SchemaValidator::validate() calls this on every single request).
     *
     * @param array<string, mixed> $rules
     */
    public static function generateKey(array $rules): string
    {
        try {
            $serialized = serialize($rules);
        } catch (\Throwable) {
            $serialized = serialize(self::normalizeForSerialization($rules));
        }

        return sha1($serialized . PHP_VERSION_ID . self::COMPILER_VERSION);
    }

    private static function normalizeForSerialization(mixed $value): mixed
    {
        if ($value instanceof \Closure) {
            return 'Closure';
        }

        if (is_array($value)) {
            return array_map(self::normalizeForSerialization(...), $value);
        }

        if (is_object($value)) {
            try {
                serialize($value);
                return $value;
            } catch (\Throwable) {
                return get_class($value);
            }
        }

        return $value;
    }

    private function compileField(CompiledField $field): string
    {
        $name = $field->getName();
        // Create a safe label for goto
        $safeName = preg_replace('/[^a-zA-Z0-9_]/', '_', $name);
        $varName = '$val_' . $safeName;
        
        $rules = $field->getRules();
        $rulesNames = array_map(function($r) {
            return (new ReflectionClass($r))->getShortName();
        }, $rules);
        $rulesStr = implode('|', $rulesNames);

        $code = "    // --- field: {$name} | rules: {$rulesStr} ---\n";
        $code .= "    {$varName} = " . $this->generateGetValueCode($field) . ";\n";

        $indent = "    ";
        $suffix = "";

        // Handle sometimes: skip if key doesn't exist
        if ($field->isSometimes()) {
            $code .= "{$indent}if (array_key_exists('" . addslashes($name) . "', \$data)) {\n";
            $indent .= "    ";
            $suffix = substr($indent, 0, -4) . "}\n" . $suffix;
        }

        // Handle nullable: skip rules if value is null
        if ($field->isNullable()) {
            $code .= "{$indent}if ({$varName} !== null) {\n";
            $indent .= "    ";
            $suffix = substr($indent, 0, -4) . "}\n" . $suffix;
        }

        foreach ($rules as $rule) {
            $inlined = $this->inlineRule($rule, $name, $varName, $indent);
            if ($inlined === null) {
                // canCompile()/findUnsupportedRules() should have caught this
                // before compile() ever reached code generation.
                throw new UnsupportedNativeRuleException(
                    'Cannot natively compile rule ' . get_class($rule) . " on field '{$name}'."
                );
            }
            $code .= $inlined;

            if ($field->isBail()) {
                $code .= "{$indent}if (isset(\$errors['" . addslashes($name) . "'])) { goto bail_{$safeName}; }\n";
            }
        }

        if ($field->isBail()) {
            $code .= "    bail_{$safeName}:\n";
        }

        $code .= "{$suffix}\n";

        return $code;
    }

    private function generateGetValueCode(CompiledField $field): string
    {
        $name = $field->getName();
        if (strpos($name, '.') === false) {
            return "\$data['" . addslashes($name) . "'] ?? null";
        }

        $parts = explode('.', $name);
        if (count($parts) === 2) {
             return "(isset(\$data['" . addslashes($parts[0]) . "']) && is_array(\$data['" . addslashes($parts[0]) . "'])) ? (\$data['" . addslashes($parts[0]) . "']['" . addslashes($parts[1]) . "'] ?? null) : null";
        }
        
        return "\\Vi\\Validation\\Execution\\DataHelper::get(\$data, '" . addslashes($name) . "')";
    }

    private function inlineRule(RuleInterface $rule, string $fieldName, string $valName, string $indent): ?string
    {
        if (!$rule instanceof NativeCompilableInterface) {
            return null;
        }

        // Non-implicit rules should skip if the value is "empty"
        // Implicit rules (Required, Accepted, etc.) handle empty values themselves.
        $isImplicit = $rule->isImplicitForNative();
        $prefix = "";
        $suffix = "";

        if (!$isImplicit) {
            $prefix = "{$indent}if (!(\$val === null || (is_string(\$val) && \$val === '') || (is_array(\$val) && \$val === []))) {\n";
            $prefix = str_replace("\$val", $valName, $prefix);
            $indent .= "    ";
            $suffix = substr($indent, 0, -4) . "}\n";
        }

        $code = $rule->compileNative(new NativeCompilationContext($fieldName, $valName, $indent));

        return $prefix . $code . $suffix;
    }
}
