<?php

declare(strict_types=1);

namespace Vi\Validation\Compilation;

use Vi\Validation\Execution\CompiledField;
use Vi\Validation\Execution\CompiledSchema;
use Vi\Validation\Rules\NativeCompilableInterface;
use Vi\Validation\Rules\RuleInterface;
use ReflectionClass;

/**
 * NativeCompiler generates highly optimized PHP code for validation schemas.
 * It inlines rules that declare themselves native-compilable to minimize
 * method calls and object allocations.
 *
 * Compatibility contract: a native validator must never change validation
 * semantics compared to ValidatorEngine. If a schema contains any rule that
 * cannot be inlined, compile() throws UnsupportedNativeRuleException instead
 * of silently omitting the rule. Callers must catch it (or check
 * canCompile() up front) and fall back to ValidatorEngine for that schema.
 *
 * Whether a rule is inlinable is never guessed from its class name: it is
 * exactly the set of rules implementing Rules\NativeCompilableInterface (see
 * isSupported()). That interface also carries the actual codegen
 * (RuleInterface::compileNative()), so this class only owns the mechanics
 * that are the same for every field - the emptiness guard, sometimes/
 * nullable/bail wrapping, and value extraction - never rule-specific logic.
 */
final class NativeCompiler
{
    public const COMPILER_VERSION = '2.0.0';

    /**
     * Check whether every rule in the schema can be natively inlined.
     *
     * Use this to decide, ahead of time, whether it is safe to call
     * compile() for a given schema.
     */
    public function canCompile(CompiledSchema $schema): bool
    {
        return $this->findUnsupportedRules($schema) === [];
    }

    /**
     * List the rules in the schema that cannot be natively inlined, as
     * "field:RuleClass" strings. An empty list means the schema is fully
     * native-compilable.
     *
     * @return list<string>
     */
    public function findUnsupportedRules(CompiledSchema $schema): array
    {
        $unsupported = [];

        foreach ($schema->getFields() as $field) {
            // exclude*/exclusion marker rules are consumed into CompiledField's exclusion
            // flags and never appear in getRules(), so compileField() has no way to see
            // them; inlining this field would silently ignore the exclusion. Refuse instead.
            if ($field->hasExclusionSemantics()) {
                $unsupported[] = $field->getName() . ':exclusion-semantics';
            }

            foreach ($field->getRules() as $rule) {
                if (!$this->isSupported($rule)) {
                    $unsupported[] = $field->getName() . ':' . get_class($rule);
                }
            }
        }

        return $unsupported;
    }

    /**
     * Whether a single rule instance can be natively inlined.
     *
     * True iff the rule implements NativeCompilableInterface - there is no
     * other path to "supported" (no class-name list, no capability
     * guessing), so a new rule is unsupported by default until it opts in.
     */
    public function isSupported(RuleInterface $rule): bool
    {
        return $rule instanceof NativeCompilableInterface;
    }

    /**
     * Compile a schema into optimized PHP code.
     *
     * @throws UnsupportedNativeRuleException if the schema contains a rule
     *         that cannot be natively inlined. Callers must fall back to
     *         ValidatorEngine in that case rather than using a partial
     *         native validator.
     */
    public function compile(CompiledSchema $schema): string
    {
        $unsupported = $this->findUnsupportedRules($schema);
        if ($unsupported !== []) {
            throw new UnsupportedNativeRuleException(
                'Cannot natively compile schema: unsupported rule(s) found: '
                . implode(', ', $unsupported)
                . '. This schema must be validated with ValidatorEngine instead.'
            );
        }

        $code = "<?php\n\n";
        $code .= "declare(strict_types=1);\n\n";
        $code .= "/**\n";
        $code .= " * Optimized validation function generated by NativeCompiler.\n";
        $code .= " * Compiler Version: " . self::COMPILER_VERSION . "\n";
        $code .= " * PHP Version: " . PHP_VERSION . " (" . PHP_VERSION_ID . ")\n";
        $code .= " * Generated at: " . date('Y-m-d H:i:s') . "\n";
        $code .= " */\n";
        $code .= "return function(array \$data) {\n";
        $code .= "    \$errors = [];\n";
        $code .= "    \$hasErrors = false;\n";
        $code .= "    \$excludedFields = [];\n\n";

        foreach ($schema->getFields() as $index => $field) {
            $code .= $this->compileField($field, $index);
        }

        $code .= "    return [\n";
        $code .= "        'valid' => !\$hasErrors,\n";
        $code .= "        'errors' => \$errors,\n";
        $code .= "        'excluded_fields' => \$excludedFields,\n";
        $code .= "    ];\n";
        $code .= "};\n";

        return $code;
    }

    /**
     * Generate a unique key for the rules that includes PHP version and compiler version.
     *
     * The raw rules array (as passed to SchemaBuilder::setRulesArray()) may contain
     * Closures (inline rule callbacks) or arbitrary RuleInterface objects, and PHP's
     * serialize() throws on a Closure rather than silently ignoring it. Since a schema
     * containing any such rule is never natively compilable anyway (see isSupported()),
     * the exact key doesn't need to be content-stable for them - it only needs to never
     * crash the caller (SchemaValidator::validate() calls this on every single request).
     *
     * @deprecated Keys derived from the raw rules array depend on the input format (and are
     *             identical for every fluent schema, whose rules array is empty). Native
     *             artifacts are now keyed by CompiledSchema::fingerprint()->artifactKey; use
     *             ValidatorCompiler::nativeKeyFor() instead.
     *
     * @param array<string, mixed> $rules
     */
    public static function generateKey(array $rules): string
    {
        try {
            $serialized = serialize($rules);
        } catch (\Throwable) {
            $serialized = serialize(self::normalizeForSerialization($rules));
        }

        return sha1($serialized . PHP_VERSION_ID . self::COMPILER_VERSION);
    }

    private static function normalizeForSerialization(mixed $value): mixed
    {
        if ($value instanceof \Closure) {
            return 'Closure';
        }

        if (is_array($value)) {
            return array_map(self::normalizeForSerialization(...), $value);
        }

        if (is_object($value)) {
            try {
                serialize($value);
                return $value;
            } catch (\Throwable) {
                return get_class($value);
            }
        }

        return $value;
    }

    private function compileField(CompiledField $field, int $index): string
    {
        $name = $field->getName();
        // Everything derived from the field name that ends up in generated code is either a
        // var_export()ed string literal or an index-based identifier - never the raw name.
        // Field names can come from request data (e.g. "items.{$id}.qty"), so they are
        // treated as untrusted here.
        $varName = '$val_' . $index;
        $label = 'bail_' . $index;
        $nameLiteral = var_export($name, true);

        $rules = $field->getRules();
        $rulesNames = array_map(function($r) {
            return (new ReflectionClass($r))->getShortName();
        }, $rules);

        $code = '    // --- field #' . $index . ': ' . self::commentSafe($name)
            . ' | rules: ' . self::commentSafe(implode('|', $rulesNames)) . " ---\n";
        $code .= "    {$varName} = " . $this->generateGetValueCode($field) . ";\n";

        // Emptiness (Laravel semantics) is evaluated once per field, not once per rule.
        $emptyVar = '$empty_' . $index;
        foreach ($rules as $rule) {
            if ($rule instanceof NativeCompilableInterface && !$rule->isImplicitForNative()) {
                $code .= "    {$emptyVar} = " . \Vi\Validation\Execution\Emptiness::nativeExpression($varName) . ";\n";
                break;
            }
        }

        $indent = "    ";
        $suffix = "";

        // Handle sometimes: skip if key doesn't exist
        if ($field->isSometimes()) {
            // Same presence semantics as ValidationContext::hasValue() (dot-notation paths).
            $presence = strpos($name, '.') === false
                ? "array_key_exists({$nameLiteral}, \$data)"
                : "\\Vi\\Validation\\Execution\\DataHelper::has(\$data, {$nameLiteral})";
            $code .= "{$indent}if ({$presence}) {\n";
            $indent .= "    ";
            $suffix = substr($indent, 0, -4) . "}\n" . $suffix;
        }

        // Handle nullable: skip rules if value is null
        if ($field->isNullable()) {
            $code .= "{$indent}if ({$varName} !== null) {\n";
            $indent .= "    ";
            $suffix = substr($indent, 0, -4) . "}\n" . $suffix;
        }

        foreach ($rules as $rule) {
            $inlined = $this->inlineRule($rule, $name, $varName, $indent, $emptyVar);
            if ($inlined === null) {
                // canCompile()/findUnsupportedRules() should have caught this
                // before compile() ever reached code generation.
                throw new UnsupportedNativeRuleException(
                    'Cannot natively compile rule ' . get_class($rule) . ' on field ' . $nameLiteral . '.'
                );
            }
            $code .= $inlined;

            if ($field->isBail()) {
                $code .= "{$indent}if (isset(\$errors[{$nameLiteral}])) { goto {$label}; }\n";
            }
        }

        if ($field->isBail()) {
            $code .= "    {$label}:\n";
        }

        $code .= "{$suffix}\n";

        return $code;
    }

    /**
     * Reduce arbitrary text to something that can't escape a `//` comment: no newlines
     * (which end the comment) and no `?>` (which ends PHP mode even inside a comment).
     */
    private static function commentSafe(string $text): string
    {
        return (string) preg_replace('/[^A-Za-z0-9_.*| -]/', '?', $text);
    }

    private function generateGetValueCode(CompiledField $field): string
    {
        $name = $field->getName();
        if (strpos($name, '.') === false) {
            return "\$data[" . var_export($name, true) . "] ?? null";
        }

        $parts = explode('.', $name);
        if (count($parts) === 2) {
            $parent = var_export($parts[0], true);
            $child = var_export($parts[1], true);

            return "(isset(\$data[{$parent}]) && is_array(\$data[{$parent}])) ? (\$data[{$parent}][{$child}] ?? null) : null";
        }

        return "\\Vi\\Validation\\Execution\\DataHelper::get(\$data, " . var_export($name, true) . ")";
    }

    private function inlineRule(RuleInterface $rule, string $fieldName, string $valName, string $indent, string $emptyVar): ?string
    {
        if (!$rule instanceof NativeCompilableInterface) {
            return null;
        }

        // Non-implicit rules should skip if the value is "empty"
        // Implicit rules (Required, Accepted, etc.) handle empty values themselves.
        $isImplicit = $rule->isImplicitForNative();
        $prefix = "";
        $suffix = "";

        if (!$isImplicit) {
            $prefix = "{$indent}if (!{$emptyVar}) {\n";
            $indent .= "    ";
            $suffix = substr($indent, 0, -4) . "}\n";
        }

        $code = $rule->compileNative(new NativeCompilationContext($fieldName, $valName, $indent));

        return $prefix . $code . $suffix;
    }
}
